### ISSUE TITLE
Error in Installation

### ISSUE THREAD

**Issue by Nirmal2310** [LooseLab/Icarust#1]
Dear @Adoni5, Thank you for making  this awesome tool for simulating real-time nanopore sequencing. I was trying to install it on my system but I am keep getting this error:

![icarust_error](https://github.com/LooseLab/Icarust/assets/62856422/57cfb21a-6779-4f71-a266-bbd5d7e76498)

As I am not familiar with Rust I request you to please help me out with this error. 

Also, is it possible to simulate the sequencing run without applying adaptive sampling via ReadFish.

Thank you in advance for helping me out.

**Comment by Nirmal2310** [comment]
Dear @Adoni5, thank you so much for your response. I updated the protoc version to 23.2 and installated Icarust however I am again getting a warnning:

![icarust_error](https://github.com/LooseLab/Icarust/assets/62856422/a767f286-77a2-4641-9afe-5b8a06c976e5)

I thought it was something to do with icarust simulation toml file so I ran the following command: 
```bash
~/Icarust/target/release/icarust -c ~/Icarust/config.ini -s ~/Icarust/Profile_tomls/config.toml -v
```
But I am getting the following error:
```bash
thread 'main' panicked at 'Failed to read kmers to string: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/impl_services/data.rs:706:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Can you please help me with this?

**Comment by Nirmal2310** [comment]
I have tried changing the path for the squiggle arrays as well as the Flow call name but the error is the same. 
As we are simulating the Nanopore what will be the flowcell name? Do we have to connect the physical device with the flow cell in it ?

**Comment by Adoni5** [comment]
So you were right about the first issue - you had swapped `-c` (the path to the config.ini file) with `-s` (The path to the config.toml file) - I'll admit that could be a distinguished a little more clearly! 

The second command you have run - 
```bash
~/Icarust/target/release/icarust -c ~/Icarust/config.ini -s ~/Icarust/Profile_tomls/config.toml -v
```

Is correct. The problem looks like the file that contains the model values for generating R10 data is not where the code expects it to be. I'm actually just updating this right now, so a much better version will be here in a couple of hours! However If you look at line 706 in `src/impl_services/data.rs`, the file the code is looking for is given there as `static/9mer_levels_v1.txt`, which is found in the root directory of Icarust. The problem I think you are having is namely that the code is looking for the file in **<Current Working Directory>/static/9mer_levels_v1.txt** which I'm guessing does not exist?

If you try running in the Icarust code containing directory (with `/static` in it), does it work?

**Comment by Adoni5** [comment]
Hey @Nirmal2310 - This is my fault, if you add `pore_type = "R9" on the line beneath `working_pore_percent`, that should fix it. Hopefully this will all be cleared up in the update!

**Comment by Nirmal2310** [comment]
@Adoni5 I tried running Icarust using the changes suggested but I am still getting the following error:

![image](https://github.com/LooseLab/Icarust/assets/62856422/3d19b455-d64b-42ec-bec6-9813758e22b4)

The config file that I used is
```bash
output_path = "/tmp/"
target_yield = 100000000000
working_pore_percent = 85
pore_type = "R9"

[parameters]
sample_name = "test"
experiment_name = "test_2_bacteria"
flowcell_name = "FA07093"
experiment_duration_set = 4800
device_id = "Bantersaurus"
position = "FenceSitter"

[[sample]]
name = "Bacteria 1"
input_genome = "/home/user/softwares/Icarust/squiggle_arrs/NC_002516.2.squiggle.npy"
mean_read_length = 20000
weight = 1

[[sample]]
name = "Bacteria 2"
input_genome = "/home/user/softwares/Icarust/squiggle_arrs/NC_003997.3.squiggle.npy"
mean_read_length = 15000
weight = 2
```
Do you think I have to change some other parameters as well. If yes, please let me know

**Comment by Adoni5** [comment]
Hi @Nirmal2310 - I've just pushed a fairly chunky update which I _hope_ should clarify and fix up a few of the issues you've been facing!

Can you `git pull` and try this again!  Thanks for your patience 👍🏼

**Comment by Nirmal2310** [comment]
Dear @Adoni5 Icarust is running perfectly after the update. Thank you so much for the help.
As of now I am closing this issue will reach out to you if any problem occur.

**Comment by Nirmal2310** [comment]
Dear @Adoni5,
Sorry to bother you again. I was testing Icarust for human data. It is working perfectly as of now however when I tried readfish with it, it is throwing error. As mentioned in the documentation I gave position argument value of simulation.toml file to the readfish as --device but it didn't work. I tried it with the value of device_id as well but it again gave the same error.
Error:
```bash
Traceback (most recent call last):
  File "/home/user/Downloads/miniconda/envs/readfish/bin/readfish", line 8, in <module>
    sys.exit(main())
  File "/home/user/Downloads/miniconda/envs/readfish/lib/python3.8/site-packages/ru/cli.py", line 43, in main
    args.func(parser, args)
  File "/home/user/Downloads/miniconda/envs/readfish/lib/python3.8/site-packages/ru/ru_gen.py", line 464, in run
    position = get_device(args.device, host=args.host, port=args.port)
  File "/home/user/Downloads/miniconda/envs/readfish/lib/python3.8/site-packages/ru/utils.py", line 927, in get_device
    raise ValueError("Could not find device {!r}".format(device))
ValueError: Could not find device 'FenceSitter'
```
This is the simulation profile I am using:
```bash
output_path = "/DATA2/Human_Icarust"
random_seed = 10
target_yield = 100000000000
working_pore_percent = 85
pore_type = "R9"

[parameters]
sample_name = "Human_STR"
experiment_name = "Hs_Normal"
flowcell_name = "FAQ1234"
experiment_duration_set = 7200
device_id = "Bantersaurus"
position = "FenceSitter"
break_read_ms = 400

[[sample]]
name = "Homo sapiens"
input_genome = "/DATA2/Human_data/"
mean_read_length = 15000
weight = 1
```
This is the command I am using for running readfish
```bash
readfish targets --device FenceSitter --experiment-name "Human Enrichment" --toml human_enrichment.toml --workers 8 --log-file human_icarust_enrichment.log --paf-log human_icarust_enrichment_paf.log --chunk-log human_icarust_enrichment_chunk.log --channels 1 2048 --run-time 7200
```
This is the config.ini file I am using for Icarust
```bash
[TLS]
cert-dir = /opt/ont/minknow/conf/rpc-certs/

[PORTS]
manager = 10000
position = 10001

[SEQUENCER]
channels = 2048
```
I request you to please help me with this. 
Thank you in advance.

**Comment by Nirmal2310** [comment]
Hi @Adoni5 ,
Thank you for your quick response. I tried doing that but it is giving the same error. For your reference I am also adding the readfish toml file:
```bash
[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "127.0.0.1"
port = 5555

[conditions]
reference = "/DATA2/reference.mmi"

[conditions.0]
name = "Human Enrichment"
control = false
min_chunks = 1
max_chunks = 6
targets = ["chr21", "chr22"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
```
Let me know if any changes are required in the toml file as well

**Comment by Adoni5** [comment]
Hi @Nirmal2310 -

Which version of readfish are you using? Is it from the `dev_staging` branch? I would have thought that setting `--port 10000` and `--device Bantersaurus` should have worked for you here, as nothing obviously wrong leaps out at me.

I'm assuming this is all happening on the same PC?

Thanks Man,
Rory

**Comment by Nirmal2310** [comment]
I am using readfish 0.0.11a4 which is downloaded using dev_staging branch as mentioned in the repository. Also while installing I changed ont-pyguppy-client-lib==6.4.2 to ont-pyguppy-client-lib==6.5.7 to match it with the guppy version installed in the system. 
Yes, all of it is running in the same PC.

**Comment by Adoni5** [comment]
Hi @Nirmal2310 - Can you try the following Icarust, readfish and readfish TOML command:

```bash
cargo run -r -- -s Profile_tomls/config.toml -v 
```

Readfish Command
```toml
readfish targets --device Bantersaurus --experiment-name test_connect --log-level info --toml /data/projects/rory_says_hi/icarust_paper_data/shared_files/human_chr_selection.toml --port 10000 --chunk-log control_icarust_R10_chunks.tsv
```

**Needs reference path updating to the `Icarust/python/mixed_ref.fa` file on your system**
```toml
[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "ipc:///tmp/.guppy"
port = 5555

[conditions]
reference = "/path/to/reference"

[conditions.0]
name = "select_one_bac"
control = false
min_chunks = 0
max_chunks = inf
targets = ["NC_003997.3",]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
```

Just tested this on my system.

I have one more question - do you know if your *Guppy* instance is listening on `ipc` or `tcp`? If you are running default Guppy GPU, you will be listening on IPC - there should be a file at `/tmp/.guppy/5555`. This might be worth checking when you try to run readfish!

**Comment by Nirmal2310** [comment]
Dear @Adoni5,
There is no such file as mixed_ref.fa inside the python directory so I just downloaded the fasta file from NCBI and concatenated them.
As of now it is not throwing any error but it is also not proceeding. It has been stuck in this state:
```bash
readfish targets --device Bantersaurus --experiment-name test_connect --log-level info --toml test.toml --port 10000 --chunk-log control_icarust_R10_chunks.tsv
2023-06-13 17:58:33,951 ru.ru_gen /home/user/Downloads/miniconda/envs/readfish/bin/readfish targets --device Bantersaurus --experiment-name test_connect --log-level info --toml test.toml --port 10000 --chunk-log control_icarust_R10_chunks.tsv
2023-06-13 17:58:33,951 ru.ru_gen batch_size=512
2023-06-13 17:58:33,951 ru.ru_gen cache_size=512
2023-06-13 17:58:33,951 ru.ru_gen channels=[1, 512]
2023-06-13 17:58:33,951 ru.ru_gen chunk_log=control_icarust_R10_chunks.tsv
2023-06-13 17:58:33,951 ru.ru_gen command=targets
2023-06-13 17:58:33,951 ru.ru_gen device=Bantersaurus
2023-06-13 17:58:33,951 ru.ru_gen dry_run=False
2023-06-13 17:58:33,951 ru.ru_gen experiment_name=test_connect
2023-06-13 17:58:33,951 ru.ru_gen func=<function run at 0x7f4b505ac670>
2023-06-13 17:58:33,951 ru.ru_gen host=127.0.0.1
2023-06-13 17:58:33,951 ru.ru_gen log_file=None
2023-06-13 17:58:33,951 ru.ru_gen log_format=%(asctime)s %(name)s %(message)s
2023-06-13 17:58:33,951 ru.ru_gen log_level=info
2023-06-13 17:58:33,951 ru.ru_gen max_unblock_read_length_seconds=5
2023-06-13 17:58:33,951 ru.ru_gen paf_log=None
2023-06-13 17:58:33,951 ru.ru_gen port=10000
2023-06-13 17:58:33,951 ru.ru_gen run_time=172800
2023-06-13 17:58:33,951 ru.ru_gen throttle=0.4
2023-06-13 17:58:33,951 ru.ru_gen toml=test.toml
2023-06-13 17:58:33,951 ru.ru_gen unblock_duration=0.1
2023-06-13 17:58:33,951 ru.ru_gen workers=1
2023-06-13 17:58:33,954 ru.ru_gen Initialising minimap2 mapper
2023-06-13 17:58:34,036 ru.ru_gen Mapper initialised
2023-06-13 17:58:34,093 ru.ru_gen This experiment has 1 region on the flowcell
2023-06-13 17:58:34,094 ru.ru_gen Using reference: /home/user/softwares/Icarust/mixed_ref.mmi
2023-06-13 17:58:34,121 ru.ru_gen Region 'select_one_bac' (control=False) has 1 contig of which 1 are in the reference. There are 2 targets (including +/- strand) representing 45.49% of the reference. Reads will be unblocked when classed as single_off or multi_off; sequenced when classed as single_on or multi_on; and polled for more data when classed as no_map or no_seq.
```

**Comment by Nirmal2310** [comment]
Okay I will try implementing  the given solution and get back to you if this works.

**Comment by Nirmal2310** [comment]
Hi @Adoni5,
ReadFish is working perfectly with Icarust.
Once again thank you so much for all the help.
